services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # --- ADD THIS SECTION FOR GPU ACCESS ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Use all available GPUs
              capabilities: [gpu]
    # ------------------------------------
    # develop:
    #   watch:
    #     # Watch Python files for changes and sync + restart
    #     - path: ./src
    #       target: /app/src
    #       action: sync+restart
    #     # Watch requirements and rebuild container
    #     - path: ./src/requirements.txt
    #       action: rebuild
    #     # Watch configuration files
    #     - path: ./.env
    #       action: rebuild
    container_name: sales_automl_app
    ports:
      - "8501:8501" # Map Streamlit's default port to localhost
    env_file:
      - .env # Pass environment variables to the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./artifacts:/app/artifacts
      - ./autogluon_models:/app/autogluon_models
      - ./service_account.json:/app/service_account.json # Mount service account JSON
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: sales_automl_mongo
    ports:
      - "27017:27017" # Expose MongoDB's default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  mongo_data:
