name: Build and Train on VM

on:
  push:
    branches:
      # IMPORTANT: Change this to your main development branch, e.g., 'main'
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"
  workflow_dispatch:

jobs:
  build-and-train-on-vm:
    name: Build and Train on GCE VM
    runs-on: ubuntu-latest

    steps:
      - name: SSH, Build, and Train
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "✅ Connected to VM. Updating repository..."
            cd ~/sales_autoML
            git checkout main # Or your main branch
            git pull

            echo "🔨 Building new Docker image and restarting services..."
            # The --build flag forces a rebuild of the 'app' service
            # The -d flag runs the container in the background
            sudo docker compose up -d --build

            echo "🚀 Triggering model training script..."
            # Now, exec into the newly started container to run the script
            sudo docker compose exec app python3 -m src.main

            echo "✅ Training pipeline finished."
