name: Build and Train on VM

on:
  # Trigger on push to the main branch
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"

  # Trigger on a weekly schedule
  schedule:
    - cron: '0 2 * * 0'

  # Trigger manually
  workflow_dispatch:

jobs:
  build-and-train-on-vm:
    name: Build and Train on GCE VM
    runs-on: ubuntu-latest

    steps:
      - name: SSH, Build, and Train
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "✅ Connected to VM. Updating repository..."
            cd ~/sales_autoML
            git checkout main
            git pull

            echo "🔨 Building new Docker image and restarting services..."
            sudo docker compose up -d --build
            
            echo "🚀 Triggering model training as a background job..."
            nohup sudo docker compose exec app python3 -m src.main > training.log 2>&1 &
            
            echo "✅ Training script started. Check 'training.log' on the VM for progress."
