name: AutoML Retrain on Data Update

on:
  push:
    paths:
      - "requirements.txt"
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - ".env.example"
      - ".github/workflows/**"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare .env
        run: cp .env.example .env

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build and run training container
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from app
