name: AutoML Retrain on Data Update

on:
  push:
    paths:
      - "data/**"
      - "requirements.txt"
      - "src/main.py"
      - "src/model_handler.py"
      - "src/feature_engineering.py"
      - "src/data_loader.py"
      - ".env"
      - ".github/workflows/**"

  schedule:
    - cron: "0 0 1 * *"

jobs:
  retrain:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 60s
          --health-timeout 20s
          --health-retries 20

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Debug - List files
      - name: List files
        run: ls -R

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Step 5: Wait for MongoDB
      - name: Wait for MongoDB
        run: |
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh mongodb:27017 --timeout=600 --strict -- echo "MongoDB is up"

      # Step 6: Run the training script
      - name: Run training script
        env:
          MONGO_URI: mongodb://root:example@mongodb:27017/
          MONGO_DB: sales_automl
        run: python -m src.main
