name: AutoML Retrain on Data Update

on:
  push:
    paths:
      - "data/**"
      - "requirements.txt"
      - "src/main.py"
      - "src/model_handler.py"
      - "src/feature_engineering.py"
      - "src/data_loader.py"
      - ".env"

  # Trigger on a schedule (monthly on the 1st at midnight UTC)
  schedule:
    - cron: "0 0 1 * *"

jobs:
  retrain:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Step 4: Run the training script
      - name: Run training script
        env:
          MONGO_URI: mongodb://root:example@mongodb:27017/ # Use the Docker service name
          MONGO_DB: sales_automl
        run: python -m src/main.py
          